// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "The White Cell’s adventure",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "The White Cell’s adventure",
            targets: ["AppModule"],
            bundleIdentifier: "lupe.The-White-Cell-s-adventure",
            teamIdentifier: "9BB2SW97R4",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
